### PR TITLE
make ios build more like android build

### PR DESCRIPTION
**Pull request by paleozogt**
The iOS build (especially Boost) is quite a bit different than it is for Android.  I've refactored the build so that iOS and Android are more similar.  In this pull request:
- Android and iOS configure their Boost packages the same way and for the same packages
- Android and iOS build ICU with the same flags
- iOS builds Boost in the platform loop (like how Android does) rather than all in one go.  This greatly simplifies the build script, as all the lipo-ing can happen in the build-all script.  This also allows the Boost build to potentially use upstream libraries that have already been built (such as ICU).
- iOS Boost build now untars to the same place that Android does (which is just cleaner)
- iOS Boost now produces the same .a files as Android (libboost_xxx as well as the combined libboost.a)

### CODE REVIEW

**Comment by mevansam** [comment]
Hi Aaron

Thanks for taking the time to make the changes. I merged in you changes but
then got errors with the boost build. So I have instead merged them to a
separate branch and I am working on resolving them and will merge it to
master once I have resolved them.

I have however, successfully merged and tested merge request #19.

Thanks
-M

**Comment by paleozogt** [comment]
Oh sorry about that.  It was working for me...  What error are you getting?

**Comment by mevansam** [comment]
The boost bootstrap script fails. When I look at the bootstrap.log file I
see this error.

ld: warning: ignoring file
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.1.sdk/usr/lib/libSystem.dylib,
file was built for unsupported file format ( 0xce 0xfa 0xed 0xfe 0x 7 0x 0
0x 0 0x 0 0x 3 0x 0 0x 0 0x 0 0x 6 0x 0 0x 0 0x 0 ) which is not the
architecture being linked (x86_64):
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator6.1.sdk/usr/lib/libSystem.dylib

I have reverted the master and merged in the other changes you made. I will
work on it later when I get some time to see what is going on. If you are
able to recreate the issue and fix it submit another merge request.

Thanks
-M

**Comment by mevansam** [comment]
I've attached the bootstrap.log file. I think the issue is that when the
bootstrap script is doing a sanity check it is creating the object code
using the default system gcc and not the one from the SDK toolchain.

**Comment by paleozogt** [comment]
Oh, that is interesting.  I definitely am not getting that error.  Perhaps my system is subtly different from yours.  I'm on 10.8.2 with XCode 4.6.

**Comment by paleozogt** [comment]
Ah, I think I figured it out: it needs the xcode 4.6 fix merged into it.  I'll file another pull request.

**Pull request merged**
