### PR TITLE
Proper tar parameters

### PR DESCRIPTION
**Pull request by lotodore**
Use proper tar parameters (fixes issue #5).

Please let me know whether you still support this repository or review pull requests etc., I've got some more stuff here but my initial issues are still open and valid. Otherwise I will continue work in this fork.
Thanks.

### CODE REVIEW

**Comment by lotodore** [comment]
Added a commit for issue #6.

**Comment by mevansam** [comment]
Sorry for the long absence, but yes I am still maintaining this repo. I have 
merged your changes. I will test it tomorrow and also take care of you patch 
request for boost::uuid. If you have already done this then submit a pull 
request and I will merge it in as well.

Thanks

-----Original Message----- 
From: lotodore
Sent: Monday, May 28, 2012 1:38 PM
To: Mevan Samaratunga
Subject: [cmoss] Proper tar parameters (#9)

Use proper tar parameters (fixes issue #5).

Please let me know whether you still support this repository or review pull 
requests etc., I've got some more stuff here but my initial issues are still 
open and valid. Otherwise I will continue work in this fork.
Thanks.

You can merge this Pull Request by running:

  git pull https://github.com/lotodore/cmoss master

Or you can view, comment on it, or merge it online at:

  https://github.com/mevansam/cmoss/pull/9

-- Commit Summary --
- Use proper tar parameters (fixes issue #5 in original repository).

-- File Changes --

M build-droid/build-libgcrypt.sh (2)
M build-droid/build-libgpg-error.sh (2)

-- Patch Links --

  https://github.com/mevansam/cmoss/pull/9.patch
  https://github.com/mevansam/cmoss/pull/9.diff

---

Reply to this email directly or view it on GitHub:
https://github.com/mevansam/cmoss/pull/9

**Comment by lotodore** [comment]
Thanks for merging, I've submitted another pull request with the modified boost includes. Great to hear that you are still there maintaining. I'll be submitting additional requests with some new scripts for other libs.

**Comment by lotodore** [comment]
I'm afraid the merge is not correct. If you check

https://github.com/mevansam/cmoss/blob/master/build-droid/build-libgpg-error.sh

you see that there is diff-data inside.

**Pull request merged**
